version: "3.1"
services:
    client:
        image: virenmistrys/vm-react-client
        restart: always
        container_name: client
        ports:
            - "3000:3000"
        links:
            - api
        networks:
            - webappnetwork
    api:
        image: virenmistrys/vm-react-api
        restart: always
        container_name: api
        ports:
            - "9000:9000"
        depends_on:
            - mongodb
        networks:
            - webappnetwork
    mongodb:
        image: mongo
        restart: always
        container_name: mongodb
        ports:
            - 27017:27017
        command: mongod --noauth --smallfiles
        networks:
            - webappnetwork  
networks:
    webappnetwork:
        driver: bridge            